driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
    name: chef_zero
    require_chef_omnibus: true
    encrypted_data_bag_secret_key_path: ".chef/secrets/encrypted_data_bag_secret"

platforms:
  - name: ubuntu-12.04

suites:
  - name: aperio-staging
    driver:
      network:
      - ["private_network", {ip: "30.30.30.30"}]
    run_list: aperio::default
