name             'aperio'
maintainer       'Serdar Sutay'
maintainer_email 'serdar@aperioapp.com'
license          'PRIVATE'
description      'Installs/Configures aperio'
long_description 'Installs/Configures aperio'
version          '0.1.0'
